{
 "title": "Kubernetes APIServer APF Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "[Limit] Flowcontrol Concurrency by Priority Level",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_request_concurrency_limit{}",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "[Total In Use] Flowcontrol Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (apiserver_flowcontrol_request_concurrency_in_use{})",
     "legendFormat": "{{flow_schema}}"
    }
   ]
  },
  {
   "title": "[In Use] Flowcontrol Concurrency by FlowSchema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_request_concurrency_in_use{}",
     "legendFormat": "{{flow_schema}}"
    }
   ]
  },
  {
   "title": "[InQueue] Flowcontrol Requests by Flowschema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_current_inqueue_requests{}",
     "legendFormat": "{{flow_schema}}"
    }
   ]
  },
  {
   "title": "[Total Rejected] Flowcontrol Requests by FlowSchema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (flow_schema) (rate(apiserver_flowcontrol_rejected_requests_total{}[5m]))",
     "legendFormat": "{{flow_schema}}"
    }
   ]
  },
  {
   "title": "[Total Rejected] Flowcontrol Requests by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (reason) (rate(apiserver_flowcontrol_rejected_requests_total{}[5m]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "[Rejected] Flowcontrol Requests by FlowSchema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(apiserver_flowcontrol_rejected_requests_total{}[5m])",
     "legendFormat": "{{flow_schema}}"
    }
   ]
  },
  {
   "title": "[Rejected] Flowcontrol Requests by (Reason, FlowSchema)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(apiserver_flowcontrol_rejected_requests_total{}[5m])",
     "legendFormat": "{{reason}}_{{flow_schema}}"
    }
   ]
  }
 ]
}